# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('computation', ['core', 'network'])
    module.source = [
        'model/computation-model.cc',
        'model/node-info.cc',
        'model/simple-computation-model.cc',
        'model/system-info-helper.cc',
        'helper/computation-model-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('computation')
    module_test.source = [
        'test/computation-model-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'computation'
    headers.source = [
        'model/computation-model.h',
        'helper/computation-model-helper.h',
        'model/node-info.h',
        'model/simple-computation-model.h',
        'model/system-info-helper.h'
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

